/* eslint-disable */

export { default as TableVideoView } from './TableVideoView'
export { default as TableFileView } from './TableFileView'
export { default as TableExampleView } from './TableExampleView'
export { default as CouponView } from './CouponView'
export { default as AdminWorkshopsView } from './AdminWorkshopsView'
export { default as AdminCoursesView } from './AdminCoursesView'
export { default as AdminTutorialView } from './AdminTutorialView'
export { default as AdminMaterialView } from './AdminMaterialView'
export { default as AdminPresetsView } from './AdminPresetsView'
export { default as AdminChallengesView } from './AdminChallengesView'
export { default as CouponsFormView } from './CouponsFormView'
export { default as CouponsContainerView } from './CouponsContainerView'
export { default as ForgotPasswordView } from './ForgotPasswordView'
export { default as LoginView } from './LoginView'
export { default as NewPasswordView } from './NewPasswordView'
export { default as RegisterView } from './RegisterView'
export { default as UserInfoView } from './UserInfoView'
export { default as WorkshopView } from './WorkshopView'
export { default as UnauthorizedView } from './UnauthorizedView'
export { default as NotFoundView } from './NotFoundView'
export { default as InternalServerErrorView } from './InternalServerErrorView'
export { default as AdminView } from './AdminView'
export { default as CheckoutView } from './CheckoutView'
export { default as CommunityView } from './CommunityView'
export { default as CourseView } from './CourseView'
export { default as DetailCategoryView } from './DetailCategoryView'
export { default as DetailProductView } from './DetailProductView'
export { default as DetailSkuView } from './DetailSkuView'
export { default as ForgotPasswordView } from './ForgotPasswordView'
export { default as IndexView } from './IndexView'
export { default as LoginView } from './LoginView'
export { default as MembersPortalView } from './MembersPortalView'
export { default as NewPasswordView } from './NewPasswordView'
export { default as OrderConfirmationView } from './OrderConfirmationView'
export { default as PaypalCheckoutView } from './PaypalCheckoutView'
export { default as RegisterView } from './RegisterView'
export { default as SubscriptionView } from './SubscriptionView'
export { default as UpdateUserInfoView } from './UpdateUserInfoView'
export { default as UserConfirmationView } from './UserConfirmationView'
export { default as WorkshopsView } from './WorkshopsView'

/* eslint-enable */